support_world: [8]
planet: '仙舟「罗浮」'
region: '流云渡'
floor: 2
start_pos: [702, 464]
next_pos_list:
  - [560, 590]
  - [559, 566]
op_list:
  - op: 'move'
    data: [696, 561]
  - op: 'patrol'
  - op: 'move'
    data: [583, 582]
  - op: 'patrol'
