support_world: [8]
planet: '仙舟「罗浮」'
region: '流云渡'
floor: 2
start_pos: [696, 454]
next_pos_list:
  - [554, 580]
  - [553, 556]
op_list:
  - op: 'move'
    data: [690, 551]
  - op: 'patrol'
  - op: 'move'
    data: [577, 572]
  - op: 'patrol'
