support_world: [3, 4, 5, 6, 7, 8]
planet: '雅利洛-VI'
region: '大矿区'
floor: 0
algo: 1
start_pos: [782, 569]
next_pos_list:
  - [850, 622]
  - [873, 630]
op_list:
  - op: 'move'
    data: [780, 628]
  - op: 'move'
    data: [753, 698]
  - op: 'patrol'
  - op: 'move'
    data: [776, 724]
  - op: 'move'
    data: [799, 702]
  - op: 'patrol'
  - op: 'move'
    data: [826, 671]
  - op: 'move'
    data: [852, 652]
  - op: 'patrol'
