support_world: [3, 4, 5, 6, 7, 8]
planet: '雅利洛-VI'
region: '残响回廊'
floor: 0
algo: 2
start_pos: [281, 1187]
next_pos_list:
  - [209, 1195]
op_list:
  - op: 'move'
    data: [233, 1186]
  - op: 'patrol'
