support_world: [8]
planet: '仙舟罗浮'
region: '廻星港'
floor: 2
start_pos: [679, 280]
next_pos_list:
  - [834, 245]
  - [852, 245]
op_list:
  - op: 'move'
    data: [734, 278]
  - op: 'patrol'
  - op: 'move'
    data: [785, 277]
  - op: 'patrol'
  - op: 'move'
    data: [830, 272]
  - op: 'patrol'
