support_world: [6, 7, 8]
planet: '仙舟「罗浮」'
region: '廻星港'
floor: 1
start_pos: [623, 767]
next_pos_list:
  - [798, 767]
  - [798, 783]
op_list:
  - op: 'move'
    data: [659, 772]
  - op: 'move'
    data: [689, 773]
  - op: 'patrol'
  - op: 'move'
    data: [715, 773]
  - op: 'move'
    data: [723, 797]
  - op: 'patrol'
  - op: 'move'
    data: [753, 782]
  - op: 'patrol'
  - op: 'move'
    data: [778, 778]
