support_world: [8]
planet: '仙舟「罗浮」'
region: '流云渡'
floor: 1
start_pos: [257, 730]
next_pos_list:
  - [545, 805]
  - [545, 777]
op_list:
  - op: 'move'
    data: [338, 751]
  - op: 'patrol'
  - op: 'move'
    data: [430, 760]
  - op: 'move'
    data: [450, 797]
  - op: 'patrol'
  - op: 'move'
    data: [520, 792]
  - op: 'patrol'
