support_world: [3, 8]
planet: '雅利洛'
region: '大矿区'
floor: 0
start_pos: [391, 659]
next_pos_list:
  - [483, 784]
  - [504, 772]
op_list:
  - op: 'move'
    data: [438, 707]
  - op: 'patrol'
  - op: 'move'
    data: [483, 723]
  - op: 'move'
    data: [483, 748]
  - op: 'patrol'
