support_world: [7, 8]
planet: '雅利洛-VI'
region: '铆钉镇'
floor: 1
start_pos: [603, 512]
next_pos_list:
  - [594, 561]
op_list:
  - op: 'move'
    data: [602, 537]
  - op: 'patrol'
  - op: 'move'
    data: [602, 551]
