support_world: [3, 4, 5, 6, 7, 8]
planet: '雅利洛-VI'
region: '铆钉镇'
floor: 1
algo: 2
start_pos: [603, 470]
next_pos_list:
  - [594, 561]
op_list:
  - op: 'no_pos_move'
    data: [603, 537]
  - op: 'patrol'
  - op: 'no_pos_move'
    data: [603, 548]
