planet: '仙舟罗浮'
region: '流云渡'
floor: 1
start_pos: [707, 1045]
next_pos_list:
  - [508, 954]
  - [506, 938]
op_list:
  - op: 'move'
    data: [704, 989]
  - op: 'move'
    data: [695, 955]
  - op: 'patrol'
  - op: 'move'
    data: [613, 951]
  - op: 'patrol'
  - op: 'move'
    data: [531, 948]
  - op: 'patrol'
