support_world: [3, 4, 8]
planet: '雅利洛-VI'
region: '铆钉镇'
floor: 1
start_pos: [687, 435]
next_pos_list:
  - [719, 356]
  - [703, 355]
op_list:
  - op: 'move'
    data: [705, 409]
  - op: 'move'
    data: [705, 387]
  - op: 'patrol'
