support_world: [3, 4, 5, 6, 7, 8]
planet: '雅利洛-VI'
region: '边缘通路'
floor: 0
algo: 2
start_pos: [657, 196]
next_pos_list:
  - [591, 204]
  - [591, 183]
op_list:
  - op: 'move'
    data: [631, 198]
  - op: 'patrol'
