planet: '仙舟罗浮'
region: '太卜司'
floor: 1
start_pos: [209, 448]
op_list:
  - op: 'move'
    data: [193, 417]
  - op: 'move'
    data: [206, 395]
  - op: 'patrol'
  - op: 'move'
    data: [207, 350]
  - op: 'patrol'
