support_world: [8]
planet: '仙舟「罗浮」'
region: '太卜司'
floor: 1
start_pos: [249, 631]
next_pos_list:
  - [293, 710]
  - [279, 728]
op_list:
  - op: 'move'
    data: [244, 690]
  - op: 'patrol'
  - op: 'move'
    data: [271, 719]
  - op: 'patrol'
