support_world: [4, 7, 8]
planet: '雅利洛-VI'
region: '残响回廊'
floor: 0
start_pos: [665, 241]
next_pos_list:
  - [793, 325]
  - [819, 325]
op_list:
  - op: 'move'
    data: [727, 247]
  - op: 'patrol'
  - op: 'move'
    data: [779, 247]
  - op: 'patrol'
  - op: 'move'
    data: [804, 262]
  - op: 'move'
    data: [805, 300]
  - op: 'patrol'
