support_world: [5, 6, 7, 8]
planet: '仙舟「罗浮」'
region: '廻星港'
floor: 1
algo: 2
start_pos: [348, 436]
next_pos_list:
  - [415, 426]
  - [418, 449]
op_list:
  - op: 'move'
    data: [393, 440]
  - op: 'patrol'
