support_world: [6, 7, 8]
planet: '仙舟「罗浮」'
region: '流云渡'
floor: 2
start_pos: [702, 392]
next_pos_list:
  - [560, 590]
  - [559, 566]
op_list:
  - op: 'move'
    data: [701, 468]
  - op: 'patrol'
  - op: 'move'
    data: [692, 565]
  - op: 'patrol'
  - op: 'move'
    data: [580, 582]
  - op: 'patrol'
