support_world: [3, 4, 5, 6, 7, 8]
planet: '雅利洛-VI'
region: '铁卫禁区'
floor: 0
algo: 2
start_pos: [1041, 588]
next_pos_list:
  - [1111, 590]
op_list:
  - op: 'slow_move'
    data: [1061, 588]
  - op: 'slow_move'
    data: [1097, 598]
