planet: '仙舟罗浮'
region: '太卜司'
floor: 1
start_pos: [209, 448]
op_list:
  - op: 'move'
    data: [193, 419]
  - op: 'move'
    data: [207, 393]
  - op: 'patrol'
  - op: 'move'
    data: [208, 358]
  - op: 'patrol'
