support_world: [7, 8]
planet: '空间站黑塔'
region: '支援舱段'
floor: 2
start_pos: [565, 362]
next_pos_list:
  - [553, 297]
  - [577, 297]
op_list:
  - op: 'move'
    data: [535, 333]
  - op: 'move'
    data: [545, 305]
