support_world: [4, 7, 8]
planet: '空间站黑塔'
region: '支援舱段'
floor: 2
start_pos: [565, 362]
next_pos_list:
  - [553, 297]
  - [577, 297]
op_list:
  - op: 'move'
    data: [565, 336]
  - op: 'move'
    data: [575, 308]
