planet: '仙舟罗浮'
region: '廻星港'
floor: 1
start_pos: [704, 751]
next_pos_list:
  - [748, 819]
  - [731, 826]
op_list:
  - op: 'move'
    data: [718, 780]
  - op: 'patrol'
  - op: 'move'
    data: [730, 803]
