author: ['DoctorReid', 'nyehueh']
planet: '空间站黑塔'
region: '基座舱段'
floor: 0
tp: '监控室'
route:
  - idx: 1
    op: 'move'
    data: [615, 191]
  - idx: 2
    op: 'disposable'
  - idx: 3
    op: 'move'
    data: [647, 190]
  - idx: 4
    op: 'slow_move'
    data: [649, 217]
  - idx: 5
    op: 'move'
    data: [647, 302]
  - idx: 6
    op: 'patrol'
  - idx: 7
    op: 'move'
    data: [664, 333]
  - idx: 8
    op: 'disposable'
  - idx: 9
    op: 'move'
    data: [633, 380]
  - idx: 10
    op: 'disposable'
  - idx: 11
    op: 'move'
    data: [597, 425]
  - idx: 12
    op: 'disposable'
