author: ['DoctorReid', 'nyehueh']
planet: '空间站黑塔'
region: '收容舱段'
floor: 1
tp: '中庭'
route:
  - idx: 1
    op: 'move'
    data: [574, 324]
  - idx: 2
    op: 'disposable'
  - idx: 3
    op: 'move'
    data: [623, 341]
  - idx: 4
    op: 'move'
    data: [655, 307]
  - idx: 5
    op: 'patrol'
  - idx: 6
    op: 'move'
    data: [676, 297]
  - idx: 7
    op: 'patrol'
  - idx: 8
    op: 'move'
    data: [698, 312]
  - idx: 9
    op: 'move'
    data: [709, 348]
  - idx: 10
    op: 'move'
    data: [737, 360]
  - idx: 11
    op: 'move'
    data: [737, 382]
  - idx: 12
    op: 'move'
    data: [726, 384]
  - idx: 13
    op: 'disposable'
  - idx: 14
    op: 'move'
    data: [712, 390]
  - idx: 15
    op: 'move'
    data: [688, 452]
  - idx: 16
    op: 'move'
    data: [663, 441]
  - idx: 17
    op: 'patrol'
  - idx: 18
    op: 'move'
    data: [622, 407]
  - idx: 19
    op: 'disposable'
