author: ['DoctorReid', 'nyehueh']
planet: '空间站黑塔'
region: '收容舱段'
floor: 1
tp: '控制中心外'
route:
  - idx: 1
    op: 'move'
    data: [380, 339]
  - idx: 2
    op: 'patrol'
  - idx: 3
    op: 'move'
    data: [386, 327]
  - idx: 4
    op: 'move'
    data: [399, 305]
  - idx: 5
    op: 'move'
    data: [397, 287]
  - idx: 6
    op: 'disposable'
  - idx: 7
    op: 'move'
    data: [397, 287]
  - idx: 8
    op: 'move'
    data: [399, 305]
  - idx: 9
    op: 'move'
    data: [385, 355]
  - idx: 10
    op: 'disposable'
  - idx: 11
    op: 'move'
    data: [385, 413]
  - idx: 12
    op: 'disposable'
  - idx: 13
    op: 'move'
    data: [395, 424]
  - idx: 14
    op: 'move'
    data: [402, 447]
  - idx: 15
    op: 'move'
    data: [442, 455]
  - idx: 16
    op: 'patrol'
  - idx: 17
    op: 'move'
    data: [427, 469]
  - idx: 18
    op: 'move'
    data: [425, 489]
  - idx: 19
    op: 'move'
    data: [443, 518]
  - idx: 20
    op: 'move'
    data: [481, 537]
  - idx: 21
    op: 'move'
    data: [557, 548]
  - idx: 22
    op: 'move'
    data: [573, 550, 2]
  - idx: 23
    op: 'disposable'
  - idx: 24
    op: 'move'
    data: [571, 557]
  - idx: 25
    op: 'slow_move'
    data: [573, 541]
  - idx: 26
    op: 'slow_move'
    data: [570, 512]
  - idx: 27
    op: 'move'
    data: [610, 514]
  - idx: 28
    op: 'move'
    data: [611, 543]
  - idx: 29
    op: 'patrol'
