author: ['DoctorReid']
planet: '空间站黑塔'
region: '禁闭舱段'
floor: 2
tp: '温床'
route:
  - idx: 1
    op: 'move'
    data: [757, 350]
  - idx: 2
    op: 'move'
    data: [773, 370]
  - idx: 3
    op: 'move'
    data: [800, 409]
  - idx: 4
    op: 'move'
    data: [818, 453]
  - idx: 5
    op: 'move'
    data: [829, 523]
  - idx: 6
    op: 'move'
    data: [824, 580]
  - idx: 7
    op: 'move'
    data: [810, 629]
  - idx: 8
    op: 'patrol'
  - idx: 9
    op: 'move'
    data: [773, 688]
  - idx: 10
    op: 'disposable'
  - idx: 11
    op: 'move'
    data: [745, 720]
  - idx: 12
    op: 'move'
    data: [703, 749]
  - idx: 13
    op: 'patrol'
