author: ['DoctorReid', 'nyehueh']
planet: '空间站黑塔'
region: '收容舱段'
floor: 1
tp: '中庭'
route:
  - op: 'move'
    data: [574, 324]
  - op: 'disposable'
  - op: 'move'
    data: [623, 341]
  - op: 'move'
    data: [655, 307]
  - op: 'patrol'
  - op: 'move'
    data: [676, 297]
  - op: 'patrol'
  - op: 'move'
    data: [698, 312]
  - op: 'move'
    data: [709, 348]
  - op: 'move'
    data: [737, 360]
  - op: 'move'
    data: [737, 382]
  - op: 'move'
    data: [726, 384]
  - op: 'disposable'
  - op: 'move'
    data: [712, 390]
  - op: 'move'
    data: [688, 452]
  - op: 'move'
    data: [663, 441]
  - op: 'patrol'
  - op: 'move'
    data: [622, 407]
  - op: 'disposable'
