author: ['DoctorReid', '龙女姬']
planet: '空间站黑塔'
region: '支援舱段'
floor: 2
tp: '存护之蕾·拟造花萼（赤）'
route:
  - op: 'move'
    data: [463, 387]
  - op: 'slow_move'
    data: [493, 389]
  - op: 'interact'
    data: '配控装置'
  - op: 'wait'
    data: ['seconds', '3']
  - op: 'wait'
    data: ['in_world', '10']
  - op: 'update_pos'
    data: [493, 387, 1]
  - op: 'move'
    data: [472, 273]
  - op: 'patrol'
  - op: 'move'
    data: [469, 486]
  - op: 'move'
    data: [393, 486]
  - op: 'patrol'
