author: ['DoctorReid']
planet: '空间站黑塔'
region: '支援舱段'
floor: 2
tp: '存护之蕾·拟造花萼（赤）'
route:
  - op: 'move'
    data: [480, 328, 1]
  - op: 'disposable'
  - op: 'move'
    data: [454, 343]
  - op: 'disposable'
  - op: 'move'
    data: [454, 380]
  - op: 'move'
    data: [485, 388]
  - op: 'interact'
    data: '配控装置'
  - op: 'wait'
    data: ['in_world', '20']
  - op: 'move'
    data: [465, 382]
  - op: 'move'
    data: [470, 275]
  - op: 'patrol'
  - op: 'move'
    data: [473, 485]
  - op: 'move'
    data: [388, 488]
  - op: 'patrol'
  - op: 'move'
    data: [392, 457]
  - op: 'disposable'
