author: ['DoctorReid', 'nyehueh']
planet: '空间站黑塔'
region: '支援舱段'
floor: 2
tp: '电力室'
route:
  - op: 'move'
    data: [158, 419]
  - op: 'disposable'
  - op: 'move'
    data: [163, 362]
  - op: 'disposable'
  - op: 'move'
    data: [186, 398]
  - op: 'disposable'
  - op: 'move'
    data: [166, 386]
  - op: 'move'
    data: [229, 382]
  - op: 'patrol'
  - op: 'move'
    data: [247, 382]
  - op: 'move'
    data: [265, 381]
  - op: 'move'
    data: [273, 314]
  - op: 'move'
    data: [314, 314]
  - op: 'patrol'
  - op: 'move'
    data: [436, 313]
  - op: 'move'
    data: [440, 234]
  - op: 'move'
    data: [406, 237]
  - op: 'disposable'
  - op: 'move'
    data: [563, 235]
  - op: 'patrol'
  - op: 'move'
    data: [632, 234]
  - op: 'move'
    data: [632, 217]
  - op: 'disposable'
