author: ['DoctorReid', '龙女姬']
planet: '空间站黑塔'
region: '支援舱段'
floor: 2
tp: '存护之蕾·拟造花萼（赤）'
route:
  - op: 'move'
    data: [473, 388]
  - op: 'slow_move'
    data: [503, 390]
  - op: 'interact'
    data: '配控装置'
  - op: 'wait'
    data: ['seconds', '3']
  - op: 'wait'
    data: ['in_world', '10']
  - op: 'update_pos'
    data: [503, 388, 1]
  - op: 'move'
    data: [482, 274]
  - op: 'patrol'
  - op: 'move'
    data: [479, 487]
  - op: 'move'
    data: [403, 487]
  - op: 'patrol'
