author: ['DoctorReid']
planet: '空间站黑塔'
region: '支援舱段'
floor: 2
tp: '电力室'
route:
  - op: 'move'
    data: [225, 379]
  - op: 'patrol'
  - op: 'move'
    data: [265, 379]
  - op: 'move'
    data: [272, 317]
  - op: 'move'
    data: [312, 311]
  - op: 'patrol'
  - op: 'move'
    data: [438, 311]
  - op: 'move'
    data: [435, 230]
  - op: 'move'
    data: [557, 233]
  - op: 'patrol'
