author: ['DoctorReid', 'nyehueh']
planet: '空间站黑塔'
region: '支援舱段'
floor: 2
tp: '电力室'
route:
  - idx: 1
    op: 'move'
    data: [163, 362]
  - idx: 2
    op: 'disposable'
  - idx: 3
    op: 'move'
    data: [158, 419]
  - idx: 4
    op: 'disposable'
  - idx: 5
    op: 'move'
    data: [184, 382]
  - idx: 6
    op: 'move'
    data: [229, 382]
  - idx: 7
    op: 'patrol'
  - idx: 8
    op: 'move'
    data: [247, 382]
  - idx: 9
    op: 'move'
    data: [265, 381]
  - idx: 10
    op: 'move'
    data: [273, 314]
  - idx: 11
    op: 'move'
    data: [314, 314]
  - idx: 12
    op: 'patrol'
  - idx: 13
    op: 'move'
    data: [436, 313]
  - idx: 14
    op: 'move'
    data: [440, 234]
  - idx: 15
    op: 'move'
    data: [406, 237]
  - idx: 16
    op: 'disposable'
  - idx: 17
    op: 'move'
    data: [490, 226]
  - idx: 18
    op: 'move'
    data: [563, 235]
  - idx: 19
    op: 'patrol'
