author: ['DoctorReid']
planet: '空间站黑塔'
region: '禁闭舱段'
floor: 2
tp: '药物制备间'
route:
  - op: 'move'
    data: [501, 831]
  - op: 'move'
    data: [446, 808]
  - op: 'disposable'
  - op: 'move'
    data: [399, 767]
  - op: 'move'
    data: [428, 725]
  - op: 'move'
    data: [392, 700]
  - op: 'disposable'
  - op: 'move'
    data: [332, 596]
  - op: 'disposable'
  - op: 'move'
    data: [350, 556]
  - op: 'disposable'
  - op: 'move'
    data: [352, 486]
  - op: 'patrol'
  - op: 'move'
    data: [348, 434]
  - op: 'patrol'
  - op: 'move'
    data: [388, 359]
  - op: 'disposable'
