support_world: [7, 8]
planet: '仙舟「罗浮」'
region: '流云渡'
floor: 1
start_pos: [524, 1289]
next_pos_list:
  - [516, 1195]
op_list:
  - op: 'move'
    data: [531, 1255]
  - op: 'patrol'
  - op: 'move'
    data: [533, 1227]
