support_world: [3, 7, 8]
planet: '仙舟「罗浮」'
region: '工造司'
floor: 0
start_pos: [376, 622]
next_pos_list:
  - [428, 689]
  - [408, 700]
op_list:
  - op: 'move'
    data: [399, 655]
  - op: 'patrol'
  - op: 'move'
    data: [409, 672]
