support_world: [8]
planet: '雅利洛'
region: '铁卫禁区'
floor: 0
start_pos: [350, 587]
next_pos_list:
  - [544, 580]
  - [544, 589]
op_list:
  - op: 'move'
    data: [382, 592]
  - op: 'patrol'
  - op: 'move'
    data: [429, 594]
  - op: 'move'
    data: [459, 599]
  - op: 'patrol'
  - op: 'move'
    data: [513, 590]
  - op: 'patrol'
  - op: 'move'
    data: [530, 587]
