name: 问题反馈-开拓力
description: 遗器副本、历战回响、模拟宇宙沉浸奖励等需要使用开拓力的场景
title: "[问题反馈] "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        ## 前置须知

        请先阅读以下文档，里面可能就有你想要的答案
        - [运行前须知](https://github.com/DoctorReid/StarRailOneDragon/wiki#12-%E8%BF%90%E8%A1%8C%E5%89%8D%E9%A1%BB%E7%9F%A5)
        - [开拓力介绍](https://github.com/DoctorReid/StarRailOneDragon/wiki/%E5%8A%9F%E8%83%BD_%E6%97%A5%E5%B8%B8#%E5%BC%80%E6%8B%93%E5%8A%9B)
        - [常见Q&A](https://github.com/DoctorReid/StarRailOneDragon/wiki/%E5%B8%B8%E8%A7%81QA)

  - type: markdown
    attributes:
      value: |
        ## 问题反馈

  - type: input
    attributes:
      label: "使用版本"
      placeholder: "例如 2.2.2"
    validations:
      required: true

  - type: input
    attributes:
      label: "问题副本"
      description: "出现问题的副本名称"
      placeholder: "例如 2.2.2"
    validations:
      required: true

  - type: textarea
    attributes:
      label: "问题描述"
      description: "尽量具体地描述产生这个问题的场景，详细的上下文有助于理解问题产生的原因。"
      placeholder: |
        历战余响，出现光锥奖励时，会卡死在光锥领取画面
    validations:
      required: true

  - type: textarea
    attributes:
      label: "游戏截图"
      description: "提供游戏截图有助于更直观地理解问题。使用脚本按F11进行截图最佳，图片保存在 .debug/images/ 文件夹中"
      placeholder: "游戏截图"

  - type: textarea
    attributes:
      label: "运行日志"
      description: "提供日志可以有助于理解脚本运行情况，日志保存在 .log/log.txt 中"
      placeholder: "运行日志"

  - type: textarea
    attributes:
      label: "你的建议"
      description: "针对这个场景，你觉得合适的解决方案是"
      placeholder: "你的建议"