name: 欢愉
path: ELATION
bless_priority:
  - BLESS_00_003
  - BLESS_07_003
  - BLESS_07_002
  - BLESS_07_008
  - BLESS_07_007
  - BLESS_07_018
  - BLESS_07_015
  - BLESS_07_013
  - BLESS_07_022
  - BLESS_07_017
  - BLESS_07_024
  - BLESS_07_014
  - BLESS_07_010
  - BLESS_07_000
level_type_priority:
  - combat
  - transaction
  - event
  - encounter
curio_priority:
  - CURIO_019
  - CURIO_021
  - CURIO_011
  - CURIO_024
  - CURIO_049
  - CURIO_018
