support_world: [8]
planet: '雅利洛-VI'
region: '铁卫禁区'
floor: 0
start_pos: [791, 942]
next_pos_list:
  - [692, 1071]
  - [696, 1087]
op_list:
  - op: 'move'
    data: [787, 1008]
  - op: 'patrol'
  - op: 'move'
    data: [786, 1058]
  - op: 'move'
    data: [743, 1099]
  - op: 'patrol'
  - op: 'move'
    data: [716, 1087]
  - op: 'patrol'
