support_world: [3, 4, 5, 6, 7, 8]
planet: '雅利洛-VI'
region: '铁卫禁区'
floor: 0
algo: 2
start_pos: [613, 566]
next_pos_list:
  - [627, 635]
  - [644, 633]
op_list:
  - op: 'move'
    data: [623, 610]
  - op: 'patrol'
