support_world: [8]
planet: '雅利洛-VI'
region: '铁卫禁区'
floor: 0
start_pos: [556, 856]
next_pos_list:
  - [296, 863]
  - [296, 851]
op_list:
  - op: 'move'
    data: [478, 857]
  - op: 'patrol'
  - op: 'move'
    data: [413, 861]
  - op: 'patrol'
  - op: 'move'
    data: [320, 859]
  - op: 'patrol'
