support_world: [8]
planet: '仙舟「罗浮」'
region: '工造司'
floor: 0
start_pos: [721, 1291]
next_pos_list:
  - [807, 1114]
  - [807, 1136]
op_list:
  - op: 'move'
    data: [723, 1221]
  - op: 'patrol'
  - op: 'move'
    data: [745, 1200]
  - op: 'patrol'
  - op: 'move'
    data: [765, 1123]
  - op: 'patrol'
  - op: 'move'
    data: [788, 1122]
