support_world: [8]
planet: '仙舟「罗浮」'
region: '工造司'
floor: 0
start_pos: [721, 1281]
next_pos_list:
  - [807, 1104]
  - [807, 1126]
op_list:
  - op: 'move'
    data: [723, 1211]
  - op: 'patrol'
  - op: 'move'
    data: [745, 1190]
  - op: 'patrol'
  - op: 'move'
    data: [765, 1113]
  - op: 'patrol'
  - op: 'move'
    data: [788, 1112]
