support_world: [7, 8]
planet: '空间站黑塔'
region: '支援舱段'
floor: 2
start_pos: [740, 399]
next_pos_list:
  - [801, 232]
  - [786, 234]
op_list:
  - op: 'move'
    data: [727, 279]
  - op: 'patrol'
  - op: 'move'
    data: [737, 265]
  - op: 'move'
    data: [780, 256]
  - op: 'patrol'
