support_world: [3, 4, 5, 6, 7, 8]
planet: '空间站黑塔'
region: '支援舱段'
floor: 2
start_pos: [740, 399]
next_pos_list:
  - [801, 232]
  - [786, 234]
op_list:
  - op: 'move'
    data: [737, 280]
  - op: 'patrol'
  - op: 'move'
    data: [747, 266]
  - op: 'move'
    data: [790, 257]
  - op: 'patrol'
