support_world: [3, 4, 5, 6, 7, 8]
planet: '雅利洛-VI'
region: '残响回廊'
floor: 0
algo: 2
start_pos: [510, 1235]
next_pos_list:
  - [626, 1228]
op_list:
  - op: 'no_pos_move'
    data: [600, 1235]
  - op: 'patrol'
