support_world: [3, 4, 5, 6, 7, 8]
planet: '空间站黑塔'
region: '支援舱段'
floor: 2
start_pos: [341, 230]
next_pos_list:
  - [421, 239]
  - [426, 221]
op_list:
  - op: 'move'
    data: [411, 230]
  - op: 'patrol'
