support_world: [3, 5, 6, 7, 8]
planet: '雅利洛-VI'
region: '大矿区'
floor: 0
algo: 1
start_pos: [687, 712]
next_pos_list:
  - [557, 706]
  - [577, 702]
op_list:
  - op: 'move'
    data: [657, 749]
  - op: 'patrol'
  - op: 'move'
    data: [628, 750]
  - op: 'patrol'
  - op: 'move'
    data: [571, 731]
  - op: 'patrol'
