support_world: [3, 4, 5, 6, 7, 8]
planet: '雅利洛-VI'
region: '残响回廊'
floor: 0
start_pos: [638, 1233]
next_pos_list:
  - [726, 1221]
reward_pos: [714, 1247]
op_list:
  - op: 'slow_move'
    data: [695, 1233]
