support_world: [3, 5, 8]
planet: '雅利洛-VI'
region: '铆钉镇'
floor: 1
start_pos: [739, 255]
next_pos_list:
  - [638, 334]
  - [619, 323]
op_list:
  - op: 'move'
    data: [695, 277]
  - op: 'patrol'
  - op: 'move'
    data: [639, 314]
  - op: 'patrol'
