PLANET_1_KZJ = "kjzht"
REGION_0_GJCX = "gjcx"
REGION_1_ZKCD = "zkcd"
REGION_2_JZCD = "jzcd"

TEMPLATE_ARROW = "loc_arrow"
TEMPLATE_ARROW_LEN = 24  # 箭头的图片大小
TEMPLATE_TRANSPORT_LEN = 50  # 传送点的图片大小

THRESHOLD_SP_TEMPLATE_IN_LARGE_MAP = 0.7  # 特殊点模板在大地图上的阈值
THRESHOLD_SP_TEMPLATE_IN_LITTLE_MAP = 0.7  # 特殊点模板在小地图上的阈值
THRESHOLD_SP_TEMPLATE_IN_LITTLE_MAP_CENTER = 0.4  # 特殊点模板在小地图中心的阈值