PLANET_1_KZJ = "kjzht"
REGION_0_GJCX = "gjcx"
REGION_1_ZKCD = "zkcd"
REGION_2_JZCD = "jzcd"

LITTLE_MAP_CENTER_ARROW_LEN = 13

TEMPLATE_ARROW = "arrow"
TEMPLATE_ARROW_LEN = 30  # 箭头的图片大小
TEMPLATE_TRANSPORT_LEN = 50  # 传送点的图片大小

THRESHOLD_SP_TEMPLATE_IN_LARGE_MAP = 0.7  # 特殊点模板在大地图上的阈值
THRESHOLD_SP_TEMPLATE_IN_LITTLE_MAP = 0.7  # 特殊点模板在小地图上的阈值
THRESHOLD_SP_TEMPLATE_IN_LITTLE_MAP_CENTER = 0.4  # 特殊点模板在小地图中心的阈值
THRESHOLD_ARROW_IN_LITTLE_MAP = 0.5  # 箭头在小地图的阈值

COLOR_WHITE_GRAY = 255  # 地图上道路颜色
COLOR_WHITE_BGR = (255, 255, 255)  # 白色
COLOR_WHITE_BGRA = (255, 255, 255, 255)  # 白色
COLOR_MAP_ROAD_GRAY = 0  # 地图上道路颜色
COLOR_MAP_ROAD_BGR = (0, 0, 0)  # 地图上道路颜色
COLOR_MAP_ROAD_BGRA = (0, 0, 0, 255)  # 地图上道路颜色
COLOR_MAP_EDGE_BGR = (0, 255, 0)  # 地图上边的颜色
COLOR_ARROW_BGRA = (255, 200, 0, 255)  # 小箭头颜色
COLOR_ARROW_ALPHA = (0, 0, 0, 0)  # 透明
