support_world: [8]
planet: '仙舟「罗浮」'
region: '工造司'
floor: 0
start_pos: [949, 408]
next_pos_list:
  - [769, 437]
  - [769, 413]
op_list:
  - op: 'move'
    data: [863, 406]
  - op: 'patrol'
  - op: 'move'
    data: [821, 409]
  - op: 'move'
    data: [793, 422]
  - op: 'patrol'
