project_name: "StarRail-OneDragon"
python_version: "3.11"
github_homepage: "https://github.com/OneDragon-Anything/StarRailOneDragon"
github_https_repository: "https://github.com/OneDragon-Anything/StarRailOneDragon.git"
github_ssh_repository: "git@github.com:OneDragon-Anything/StarRailOneDragon.git"
gitee_https_repository: "https://gitee.com/OneDragon-Anything/StarRailOneDragon.git"
gitee_ssh_repository: "git@gitee.com:OneDragon-Anything/StarRailOneDragon.git"
project_git_branch: "main"
requirements: "requirements-prod.txt"
screen_standard_width: 1920
screen_standard_height: 1080
qq_link: ""
quick_start_link: "http://onedragon-anything.github.io/sr/zh/quickstart.html"