project_name: "StarRail-OneDragon"
python_version: "3.11.9"
github_homepage: "https://github.com/DoctorReid/StarRailOneDragon"
github_https_repository: "https://github.com/DoctorReid/StarRailOneDragon.git"
github_ssh_repository: "git@github.com:DoctorReid/StarRailOneDragon.git"
gitee_https_repository: "https://gitee.com/doctorreid/StarRailOneDragon.git"
gitee_ssh_repository: "git@gitee.com:doctorreid/StarRailOneDragon.git"
project_git_branch: "main"
requirements: "requirements-prod.txt"
screen_standard_width: 1920
screen_standard_height: 1080
