team_module_list:
- character_id_list:
  - jingliu
  - ruanmei
  - pela
  - fuxuan
  enable_fh: true
  enable_pf: false
  module_name: "\u5168\u51B0"
- character_id_list:
  - jingliu
  - ruanmei
  - silverwolf
  - fuxuan
  enable_fh: true
  enable_pf: false
  module_name: "\u91CF\u5B50"
- character_id_list:
  - danhengimbibitorlunae
  - hanya
  - tingyun
  - luocha
  enable_fh: true
  enable_pf: false
  module_name: "\u865A\u6570"
- character_id_list:
  - clara
  - yukong
  - tingyun
  - luocha
  enable_fh: true
  enable_pf: false
  module_name: "\u7269\u7406"
