support_world: [3, 7, 8]
planet: '空间站黑塔'
region: '支援舱段'
floor: 2
start_pos: [143, 537]
next_pos_list:
  - [227, 368]
  - [227, 388]
op_list:
  - op: 'move'
    data: [140, 508]
  - op: 'patrol'
  - op: 'move'
    data: [141, 399]
  - op: 'patrol'
  - op: 'move'
    data: [202, 380]
  - op: 'patrol'
