support_world: [5, 6, 7, 8]
planet: '仙舟「罗浮」'
region: '廻星港'
floor: 1
algo: 2
start_pos: [704, 751]
next_pos_list:
  - [748, 819]
  - [731, 826]
op_list:
  - op: 'move'
    data: [718, 780]
  - op: 'patrol'
  - op: 'move'
    data: [730, 803]
