planet: '仙舟罗浮'
region: '廻星港'
floor: 1
start_pos: [363, 285]
op_list:
  - op: 'move'
    data: [322, 354]
  - op: 'patrol'
  - op: 'move'
    data: [316, 426]
  - op: 'move'
    data: [348, 435]
  - op: 'patrol'
