support_world: [8]
planet: '仙舟「罗浮」'
region: '丹鼎司'
floor: 1
start_pos: [531, 711]
next_pos_list:
  - [455, 718]
  - [455, 703]
op_list:
  - op: 'move'
    data: [487, 709]
  - op: 'patrol'
  - op: 'move'
    data: [471, 710]
