support_world: [3, 4, 5, 6, 7, 8]
planet: '雅利洛-VI'
region: '大矿区'
floor: 0
algo: 2
start_pos: [352, 574]
next_pos_list:
  - [305, 519]
op_list:
  - op: 'no_pos_move'
    data: [328, 534]
  - op: 'patrol'
