support_world: [3, 4, 5, 6, 7, 8]
planet: '雅利洛-VI'
region: '大矿区'
floor: 0
algo: 2
start_pos: [360, 586]
next_pos_list:
  - [313, 531]
op_list:
  - op: 'no_pos_move'
    data: [336, 546]
  - op: 'patrol'
