support_world: [8]
planet: '仙舟「罗浮」'
region: '太卜司'
floor: 1
algo: 2
start_pos: [209, 463]
next_pos_list:
  - [197, 348]
  - [221, 348]
op_list:
  - op: 'move'
    data: [193, 434]
  - op: 'move'
    data: [207, 408]
  - op: 'patrol'
  - op: 'move'
    data: [208, 373]
  - op: 'patrol'
