support_world: [3, 4, 5, 6, 7, 8]
planet: '空间站黑塔'
region: '支援舱段'
floor: 2
algo: 2
start_pos: [565, 378]
next_pos_list:
  - [553, 298]
  - [577, 298]
op_list:
  - op: 'no_pos_move'
    data: [565, 325]
  - op: 'patrol'
