support_world: [3, 7, 8]
planet: '空间站黑塔'
region: '支援舱段'
floor: 2
start_pos: [575, 378]
next_pos_list:
  - [563, 298]
  - [587, 298]
op_list:
  - op: 'move'
    data: [572, 349]
  - op: 'move'
    data: [572, 323]
  - op: 'patrol'
