support_world: [3, 4, 5, 6, 7, 8]
planet: '空间站黑塔'
region: '收容舱段'
floor: 1
algo: 2
start_pos: [409, 271]
next_pos_list:
  - [326, 235]
  - [331, 224]
op_list:
  - op: 'move'
    data: [357, 254]
  - op: 'move'
    data: [342, 245]
  - op: 'patrol'
