author: ['DoctorReid']
planet: '雅利洛-VI'
region: '大矿区'
floor: 0
tp: '锋芒之形·凝滞虚影'
route:
  - idx: 1
    op: 'move'
    data: [513, 531]
  - idx: 2
    op: 'move'
    data: [438, 545]
  - idx: 3
    op: 'patrol'
  - idx: 4
    op: 'move'
    data: [382, 519]
  - idx: 5
    op: 'move'
    data: [392, 501]
  - idx: 6
    op: 'disposable'
  - idx: 7
    op: 'move'
    data: [382, 519]
  - idx: 8
    op: 'move'
    data: [434, 526]
  - idx: 9
    op: 'move'
    data: [443, 491]
  - idx: 10
    op: 'patrol'
  - idx: 11
    op: 'move'
    data: [446, 462]
  - idx: 12
    op: 'move'
    data: [486, 440]
  - idx: 13
    op: 'patrol'
