author: ['DoctorReid']
planet: '雅利洛-VI'
region: '城郊雪原'
floor: 0
tp: '回忆之蕾·拟造花萼（金）'
route:
  - idx: 1
    op: 'move'
    data: [1106, 444]
  - idx: 2
    op: 'disposable'
  - idx: 3
    op: 'move'
    data: [1064, 489]
  - idx: 4
    op: 'patrol'
  - idx: 5
    op: 'move'
    data: [981, 584]
  - idx: 6
    op: 'move'
    data: [937, 474]
  - idx: 7
    op: 'patrol'
  - idx: 8
    op: 'move'
    data: [1012, 407]
  - idx: 9
    op: 'disposable'
  - idx: 10
    op: 'move'
    data: [1019, 278]
  - idx: 11
    op: 'disposable'
  - idx: 12
    op: 'move'
    data: [974, 313]
  - idx: 13
    op: 'disposable'
  - idx: 14
    op: 'move'
    data: [890, 254]
  - idx: 15
    op: 'disposable'
  - idx: 16
    op: 'move'
    data: [704, 326]
  - idx: 17
    op: 'patrol'
  - idx: 18
    op: 'move'
    data: [689, 227]
  - idx: 19
    op: 'patrol'
  - idx: 20
    op: 'move'
    data: [710, 229]
  - idx: 21
    op: 'disposable'
  - idx: 22
    op: 'move'
    data: [624, 292]
  - idx: 23
    op: 'disposable'
  - idx: 24
    op: 'move'
    data: [570, 235]
  - idx: 25
    op: 'disposable'
