author: ['DoctorReid', 'nyehueh']
planet: '雅利洛-VI'
region: '残响回廊'
floor: 0
tp: '古战场前线'
route:
  - idx: 1
    op: 'disposable'
  - idx: 2
    op: 'move'
    data: [487, 1232]
  - idx: 3
    op: 'move'
    data: [450, 1257]
  - idx: 4
    op: 'disposable'
  - idx: 5
    op: 'move'
    data: [489, 1230]
  - idx: 6
    op: 'move'
    data: [489, 1133]
  - idx: 7
    op: 'patrol'
  - idx: 8
    op: 'move'
    data: [485, 1178]
  - idx: 9
    op: 'move'
    data: [422, 1180]
  - idx: 10
    op: 'move'
    data: [388, 1184]
  - idx: 11
    op: 'move'
    data: [351, 1189]
  - idx: 12
    op: 'patrol'
  - idx: 13
    op: 'move'
    data: [272, 1185]
  - idx: 14
    op: 'disposable'
  - idx: 15
    op: 'move'
    data: [265, 1238]
  - idx: 16
    op: 'disposable'
  - idx: 17
    op: 'move'
    data: [265, 1321]
  - idx: 18
    op: 'patrol'
  - idx: 19
    op: 'move'
    data: [297, 1322]
  - idx: 20
    op: 'patrol'
  - idx: 21
    op: 'move'
    data: [355, 1322]
  - idx: 22
    op: 'disposable'
