author: ['DoctorReid']
planet: '雅利洛-VI'
region: '大矿区'
floor: 0
tp: '俯瞰点'
route:
  - idx: 1
    op: 'move'
    data: [616, 657]
  - idx: 2
    op: 'move'
    data: [679, 642]
  - idx: 3
    op: 'move'
    data: [694, 574]
  - idx: 4
    op: 'patrol'
  - idx: 5
    op: 'move'
    data: [770, 565]
  - idx: 6
    op: 'move'
    data: [781, 617]
  - idx: 7
    op: 'disposable'
  - idx: 8
    op: 'move'
    data: [768, 638]
  - idx: 9
    op: 'move'
    data: [732, 688]
  - idx: 10
    op: 'move'
    data: [781, 709]
  - idx: 11
    op: 'disposable'
  - idx: 12
    op: 'move'
    data: [732, 688]
  - idx: 13
    op: 'move'
    data: [706, 705]
  - idx: 14
    op: 'move'
    data: [687, 709]
  - idx: 15
    op: 'patrol'
  - idx: 16
    op: 'move'
    data: [642, 742]
  - idx: 17
    op: 'patrol'
  - idx: 18
    op: 'move'
    data: [596, 735]
  - idx: 19
    op: 'move'
    data: [555, 720]
  - idx: 20
    op: 'move'
    data: [531, 744]
  - idx: 21
    op: 'move'
    data: [487, 723]
  - idx: 22
    op: 'disposable'
  - idx: 23
    op: 'move'
    data: [397, 682]
  - idx: 24
    op: 'patrol'
  - idx: 25
    op: 'move'
    data: [376, 622]
  - idx: 26
    op: 'patrol'
  - idx: 27
    op: 'move'
    data: [413, 611]
  - idx: 28
    op: 'move'
    data: [467, 665]
  - idx: 29
    op: 'move'
    data: [497, 662]
  - idx: 30
    op: 'move'
    data: [521, 628]
  - idx: 31
    op: 'patrol'
