author: ['DoctorReid', 'nyehueh']
planet: '雅利洛-VI'
region: '残响回廊'
floor: 0
tp: '筑城领域'
route:
  - idx: 1
    op: 'disposable'
  - idx: 2
    op: 'move'
    data: [774, 406]
  - idx: 3
    op: 'move'
    data: [803, 398]
  - idx: 4
    op: 'move'
    data: [807, 310]
  - idx: 5
    op: 'disposable'
  - idx: 6
    op: 'move'
    data: [800, 232]
  - idx: 7
    op: 'patrol'
  - idx: 8
    op: 'move'
    data: [777, 264]
  - idx: 9
    op: 'disposable'
