author: ['DoctorReid', 'nyehueh']
planet: '雅利洛-VI'
region: '残响回廊'
floor: 0
tp: '作战指挥室'
route:
  - idx: 1
    op: 'move'
    data: [470, 916]
  - idx: 2
    op: 'patrol'
  - idx: 3
    op: 'move'
    data: [472, 952]
  - idx: 4
    op: 'patrol'
