author: ['DoctorReid']
planet: '雅利洛-VI'
region: '大矿区'
floor: 0
tp: '锋芒之形·凝滞虚影'
route:
  - idx: 1
    op: 'move'
    data: [521, 543]
  - idx: 2
    op: 'move'
    data: [446, 557]
  - idx: 3
    op: 'patrol'
  - idx: 4
    op: 'move'
    data: [390, 531]
  - idx: 5
    op: 'move'
    data: [400, 513]
  - idx: 6
    op: 'disposable'
  - idx: 7
    op: 'move'
    data: [390, 531]
  - idx: 8
    op: 'move'
    data: [442, 538]
  - idx: 9
    op: 'move'
    data: [451, 503]
  - idx: 10
    op: 'patrol'
  - idx: 11
    op: 'move'
    data: [454, 474]
  - idx: 12
    op: 'move'
    data: [494, 452]
  - idx: 13
    op: 'patrol'
