author: ['DoctorReid', 'nyehueh']
planet: '雅利洛-VI'
region: '残响回廊'
floor: 0
tp: '鸣雷之形·凝滞虚影'
route:
  - idx: 1
    op: 'move'
    data: [485, 617]
  - idx: 2
    op: 'move'
    data: [486, 490]
  - idx: 3
    op: 'move'
    data: [487, 452]
  - idx: 4
    op: 'move'
    data: [499, 441]
  - idx: 5
    op: 'patrol'
