author: ['DoctorReid']
planet: '雅利洛-VI'
region: '残响回廊'
floor: 0
tp: '鸣雷之形·凝滞虚影'
route:
  - op: 'move'
    data: [488, 630]
  - op: 'move'
    data: [484, 606]
  - op: 'move'
    data: [486, 453]
  - op: 'move'
    data: [507, 436]
  - op: 'patrol'
