author: ['DoctorReid']
planet: '雅利洛-VI'
region: '永冬岭'
floor: 0
tp: '古战场雪原'
route:
  - idx: 1
    op: 'move'
    data: [428, 782]
  - idx: 2
    op: 'disposable'
  - idx: 3
    op: 'move'
    data: [486, 785]
  - idx: 4
    op: 'move'
    data: [485, 663]
  - idx: 5
    op: 'move'
    data: [462, 609]
  - idx: 6
    op: 'move'
    data: [482, 540]
  - idx: 7
    op: 'patrol'
