author: ['DoctorReid']
planet: '雅利洛'
region: '大矿区'
floor: 0
tp: '锋芒之形·凝滞虚影'
route:
  - op: 'move'
    data: [434, 526]
  - op: 'patrol'
  - op: 'move'
    data: [443, 491]
  - op: 'move'
    data: [446, 462]
  - op: 'move'
    data: [486, 440]
  - op: 'patrol'
