author: ['DoctorReid']
planet: '雅利洛-VI'
region: '铆钉镇'
floor: 1
tp: '孤儿院'
route:
  - idx: 1
    op: 'move'
    data: [602, 198]
  - idx: 2
    op: 'move'
    data: [638, 187]
  - idx: 3
    op: 'move'
    data: [685, 195]
  - idx: 4
    op: 'patrol'
  - idx: 5
    op: 'move'
    data: [683, 229]
  - idx: 6
    op: 'move'
    data: [707, 281]
  - idx: 7
    op: 'move'
    data: [683, 272]
  - idx: 8
    op: 'disposable'
  - idx: 9
    op: 'move'
    data: [657, 320]
  - idx: 10
    op: 'disposable'
