author: ['DoctorReid']
planet: '雅利洛-VI'
region: '铆钉镇'
floor: 1
tp: '孤儿院'
route:
  - op: 'move'
    data: [596, 195]
  - op: 'move'
    data: [632, 184]
  - op: 'move'
    data: [679, 192]
  - op: 'patrol'
