author: ['DoctorReid']
planet: '雅利洛-VI'
region: '铆钉镇'
floor: 1
tp: '孤儿院'
route:
  - idx: 1
    op: 'move'
    data: [596, 195]
  - idx: 2
    op: 'move'
    data: [632, 184]
  - idx: 3
    op: 'move'
    data: [679, 192]
  - idx: 4
    op: 'patrol'
  - idx: 5
    op: 'move'
    data: [701, 278]
  - idx: 6
    op: 'move'
    data: [677, 269]
  - idx: 7
    op: 'disposable'
  - idx: 8
    op: 'move'
    data: [651, 317]
  - idx: 9
    op: 'disposable'
