support_world: [3, 4, 5, 6, 7, 8]
planet: '空间站黑塔'
region: '收容舱段'
floor: 1
algo: 1
start_pos: [929, 244]
next_pos_list:
  - [824, 339]
  - [805, 340]
op_list:
  - op: 'move'
    data: [903, 284]
  - op: 'move'
    data: [871, 271]
  - op: 'patrol'
  - op: 'move'
    data: [883, 268]
  - op: 'move'
    data: [853, 275]
  - op: 'move'
    data: [808, 287]
  - op: 'move'
    data: [811, 309]
  - op: 'move'
    data: [814, 327]
  - op: 'patrol'
