planet: '雅利洛'
region: '边缘通路'
floor: 0
start_pos: [770, 865]
op_list:
  - op: 'move'
    data: [802, 900]
  - op: 'move'
    data: [835, 912]
  - op: 'patrol'
  - op: 'move'
    data: [835, 961]
  - op: 'patrol'
  - op: 'move'
    data: [781, 955]
  - op: 'patrol'
