support_world: [6, 8]
planet: '仙舟「罗浮」'
region: '流云渡'
floor: 1
start_pos: [707, 1045]
next_pos_list:
  - [508, 954]
  - [506, 938]
op_list:
  - op: 'move'
    data: [710, 999]
  - op: 'move'
    data: [701, 965]
  - op: 'patrol'
  - op: 'move'
    data: [681, 960]
  - op: 'move'
    data: [619, 961]
  - op: 'patrol'
  - op: 'move'
    data: [537, 958]
  - op: 'patrol'
