support_world: [6, 7, 8]
planet: '空间站黑塔'
region: '支援舱段'
floor: 2
start_pos: [804, 392]
next_pos_list:
  - [785, 235]
  - [800, 234]
op_list:
  - op: 'move'
    data: [739, 386]
  - op: 'patrol'
  - op: 'move'
    data: [734, 283]
  - op: 'patrol'
  - op: 'move'
    data: [744, 266]
  - op: 'move'
    data: [790, 256]
  - op: 'patrol'
