support_world: [7, 8]
planet: '空间站黑塔'
region: '支援舱段'
floor: 2
start_pos: [814, 392]
next_pos_list:
  - [795, 235]
  - [810, 234]
op_list:
  - op: 'move'
    data: [749, 387]
  - op: 'patrol'
  - op: 'move'
    data: [744, 284]
  - op: 'patrol'
  - op: 'move'
    data: [754, 267]
  - op: 'move'
    data: [800, 257]
  - op: 'patrol'
