support_world: [6, 7, 8]
planet: '空间站黑塔'
region: '支援舱段'
floor: 2
start_pos: [804, 392]
next_pos_list:
  - [785, 235]
  - [800, 234]
op_list:
  - op: 'move'
    data: [729, 385]
  - op: 'patrol'
  - op: 'move'
    data: [724, 282]
  - op: 'patrol'
  - op: 'move'
    data: [734, 265]
  - op: 'move'
    data: [780, 255]
  - op: 'patrol'
