support_world: [3, 5, 6, 7, 8]
planet: '雅利洛-VI'
region: '铆钉镇'
floor: 1
start_pos: [629, 326]
next_pos_list:
  - [752, 244]
  - [756, 260]
op_list:
  - op: 'move'
    data: [668, 296]
  - op: 'patrol'
  - op: 'move'
    data: [735, 264]
  - op: 'patrol'
