author: ['DoctorReid']
planet: '仙舟「罗浮」'
region: '廻星港'
floor: 1
tp: '植船区萌甲'
route:
  - idx: 1
    op: 'move'
    data: [441, 489]
  - idx: 2
    op: 'move'
    data: [421, 487]
  - idx: 3
    op: 'move'
    data: [421, 445]
  - idx: 4
    op: 'move'
    data: [401, 438]
  - idx: 5
    op: 'patrol'
  - idx: 6
    op: 'move'
    data: [384, 398]
  - idx: 7
    op: 'disposable'
  - idx: 8
    op: 'move'
    data: [444, 398]
  - idx: 9
    op: 'move'
    data: [482, 398]
  - idx: 10
    op: 'move'
    data: [495, 421]
  - idx: 11
    op: 'disposable'
  - idx: 12
    op: 'move'
    data: [473, 338]
  - idx: 13
    op: 'disposable'
  - idx: 14
    op: 'move'
    data: [521, 323]
  - idx: 15
    op: 'patrol'
