author: ['DoctorReid', '龙女姬']
planet: '仙舟「罗浮」'
region: '丹鼎司'
floor: 2
tp: '药使之径·侵蚀隧洞'
route:
  - idx: 1
    op: 'move'
    data: [666, 1464]
  - idx: 2
    op: 'move'
    data: [692, 1444]
  - idx: 3
    op: 'disposable'
  - idx: 4
    op: 'move'
    data: [685, 1399]
  - idx: 5
    op: 'patrol'
  - idx: 6
    op: 'move'
    data: [712, 1422]
  - idx: 7
    op: 'disposable'
  - idx: 8
    op: 'move'
    data: [713, 1368]
  - idx: 9
    op: 'move'
    data: [760, 1325]
  - idx: 10
    op: 'patrol'
