author: ['DoctorReid']
planet: '仙舟「罗浮」'
region: '鳞渊境'
floor: 0
tp: '毁灭之蕾·拟造花萼（赤）'
route:
  - idx: 1
    op: 'move'
    data: [882, 671]
  - idx: 2
    op: 'move'
    data: [843, 638]
  - idx: 3
    op: 'move'
    data: [793, 602]
  - idx: 4
    op: 'move'
    data: [698, 586]
  - idx: 5
    op: 'patrol'
  - idx: 6
    op: 'move'
    data: [692, 549]
  - idx: 7
    op: 'patrol'
