author: ['DoctorReid', '龙女姬']
planet: '仙舟「罗浮」'
region: '工造司'
floor: 0
tp: '格物院通道'
route:
  - idx: 1
    op: 'move'
    data: [490, 494]
  - idx: 2
    op: 'move'
    data: [514, 557]
  - idx: 3
    op: 'move'
    data: [514, 649]
  - idx: 4
    op: 'patrol'
  - idx: 5
    op: 'slow_move'
    data: [540, 649]
  - idx: 6
    op: 'patrol'
  - idx: 7
    op: 'move'
    data: [540, 669]
  - idx: 8
    op: 'move'
    data: [540, 754]
  - idx: 9
    op: 'move'
    data: [553, 787]
  - idx: 10
    op: 'disposable'
  - idx: 11
    op: 'move'
    data: [508, 770]
  - idx: 12
    op: 'patrol'
  - idx: 13
    op: 'move'
    data: [470, 761]
  - idx: 14
    op: 'disposable'
  - idx: 15
    op: 'move'
    data: [499, 812]
  - idx: 16
    op: 'move'
    data: [498, 870]
  - idx: 17
    op: 'patrol'
  - idx: 18
    op: 'move'
    data: [499, 919]
  - idx: 19
    op: 'disposable'
  - idx: 20
    op: 'move'
    data: [499, 979]
  - idx: 21
    op: 'move'
    data: [475, 1003]
  - idx: 22
    op: 'move'
    data: [422, 1003]
  - idx: 23
    op: 'move'
    data: [414, 1021]
  - idx: 24
    op: 'move'
    data: [414, 1048]
  - idx: 25
    op: 'move'
    data: [403, 1110]
  - idx: 26
    op: 'move'
    data: [410, 1168]
  - idx: 27
    op: 'patrol'
  - idx: 28
    op: 'move'
    data: [426, 1220]
  - idx: 29
    op: 'patrol'
  - idx: 30
    op: 'move'
    data: [443, 1197]
  - idx: 31
    op: 'disposable'
