author: ['DoctorReid']
planet: '仙舟「罗浮」'
region: '流云渡'
floor: 1
tp: '积玉坊'
route:
  - idx: 1
    op: 'move'
    data: [537, 767]
  - idx: 2
    op: 'move'
    data: [596, 767]
  - idx: 3
    op: 'move'
    data: [658, 733]
  - idx: 4
    op: 'disposable'
  - idx: 5
    op: 'move'
    data: [725, 736]
  - idx: 6
    op: 'move'
    data: [786, 730]
  - idx: 7
    op: 'move'
    data: [821, 753]
  - idx: 8
    op: 'disposable'
  - idx: 9
    op: 'move'
    data: [857, 763]
  - idx: 10
    op: 'disposable'
  - idx: 11
    op: 'move'
    data: [846, 664]
  - idx: 12
    op: 'patrol'
  - idx: 13
    op: 'move'
    data: [861, 680]
  - idx: 14
    op: 'patrol'
  - idx: 15
    op: 'move'
    data: [891, 680]
  - idx: 16
    op: 'patrol'
