author: ['DoctorReid']
planet: '仙舟「罗浮」'
region: '绥园'
floor: 0
tp: '谈狐林后门'
route:
  - idx: 1
    op: 'move'
    data: [234, 444]
  - idx: 2
    op: 'move'
    data: [245, 418]
  - idx: 3
    op: 'move'
    data: [234, 375]
  - idx: 4
    op: 'move'
    data: [240, 333]
  - idx: 5
    op: 'patrol'
  - idx: 6
    op: 'move'
    data: [275, 333]
  - idx: 7
    op: 'move'
    data: [293, 327]
  - idx: 8
    op: 'move'
    data: [293, 357]
  - idx: 9
    op: 'patrol'
  - idx: 10
    op: 'move'
    data: [293, 310]
  - idx: 11
    op: 'disposable'
  - idx: 12
    op: 'move'
    data: [368, 335]
  - idx: 13
    op: 'patrol'
