author: ['DoctorReid']
planet: '仙舟「罗浮」'
region: '廻星港'
floor: 2
tp: '飞星小筑'
route:
  - idx: 1
    op: 'move'
    data: [834, 275]
  - idx: 2
    op: 'move'
    data: [789, 276]
  - idx: 3
    op: 'move'
    data: [736, 275]
  - idx: 4
    op: 'move'
    data: [703, 283]
  - idx: 5
    op: 'move'
    data: [673, 292]
  - idx: 6
    op: 'move'
    data: [710, 299]
  - idx: 7
    op: 'patrol'
  - idx: 8
    op: 'move'
    data: [739, 319]
  - idx: 9
    op: 'move'
    data: [788, 321]
  - idx: 10
    op: 'move'
    data: [846, 327]
  - idx: 11
    op: 'move'
    data: [883, 316]
  - idx: 12
    op: 'disposable'
  - idx: 13
    op: 'move'
    data: [846, 327]
  - idx: 14
    op: 'move'
    data: [849, 374]
  - idx: 15
    op: 'move'
    data: [770, 396]
  - idx: 16
    op: 'patrol'
  - idx: 17
    op: 'move'
    data: [858, 413]
  - idx: 18
    op: 'move'
    data: [900, 441]
  - idx: 19
    op: 'disposable'
  - idx: 20
    op: 'move'
    data: [861, 439]
  - idx: 21
    op: 'move'
    data: [802, 444]
  - idx: 22
    op: 'move'
    data: [801, 475]
  - idx: 23
    op: 'move'
    data: [850, 477]
  - idx: 24
    op: 'patrol'
