author: ['DoctorReid']
planet: '仙舟「罗浮」'
region: '绥园'
floor: 0
tp: '丰饶之蕾·拟造花萼（赤）'
route:
  - idx: 1
    op: 'move'
    data: [236, 755]
  - idx: 2
    op: 'patrol'
  - idx: 3
    op: 'move'
    data: [285, 740]
  - idx: 4
    op: 'disposable'
  - idx: 5
    op: 'move'
    data: [303, 765]
  - idx: 6
    op: 'move'
    data: [339, 771]
  - idx: 7
    op: 'disposable'
  - idx: 8
    op: 'move'
    data: [361, 776]
  - idx: 9
    op: 'move'
    data: [380, 802]
  - idx: 10
    op: 'patrol'
  - idx: 11
    op: 'move'
    data: [360, 860]
  - idx: 12
    op: 'patrol'
  - idx: 13
    op: 'move'
    data: [295, 863]
  - idx: 14
    op: 'patrol'
