author: ['DoctorReid', '龙女姬']
planet: '仙舟「罗浮」'
region: '太卜司'
floor: 1
tp: '界寰阵'
route:
  - op: 'move'
    data: [320, 297]
  - op: 'move'
    data: [294, 324]
  - op: 'move'
    data: [288, 405]
  - op: 'move'
    data: [302, 409]
  - op: 'patrol'
  - op: 'move'
    data: [286, 435]
  - op: 'patrol'
  - op: 'move'
    data: [230, 435]
  - op: 'move'
    data: [231, 422]
  - op: 'patrol'
  - op: 'move'
    data: [229, 404]
  - op: 'patrol'
  - op: 'move'
    data: [192, 404]
  - op: 'move'
    data: [192, 435]
  - op: 'patrol'
  - op: 'move'
    data: [230, 435]
  - op: 'move'
    data: [288, 435]
  - op: 'move'
    data: [285, 535]
  - op: 'move'
    data: [330, 578]
  - op: 'move'
    data: [378, 595]
  - op: 'move'
    data: [403, 650]
  - op: 'move'
    data: [436, 681]
  - op: 'move'
    data: [522, 685]
  - op: 'patrol'
