author: ['DoctorReid', '龙女姬']
planet: '仙舟「罗浮」'
region: '太卜司'
floor: 1
tp: '界寰阵'
route:
  - op: 'move'
    data: [320, 282]
  - op: 'move'
    data: [294, 309]
  - op: 'move'
    data: [288, 390]
  - op: 'move'
    data: [302, 394]
  - op: 'patrol'
  - op: 'move'
    data: [286, 420]
  - op: 'patrol'
  - op: 'move'
    data: [230, 420]
  - op: 'move'
    data: [231, 407]
  - op: 'patrol'
  - op: 'move'
    data: [229, 389]
  - op: 'patrol'
  - op: 'move'
    data: [192, 389]
  - op: 'move'
    data: [192, 420]
  - op: 'patrol'
  - op: 'move'
    data: [230, 420]
  - op: 'move'
    data: [288, 420]
  - op: 'move'
    data: [285, 520]
  - op: 'move'
    data: [330, 563]
  - op: 'move'
    data: [378, 580]
  - op: 'move'
    data: [403, 635]
  - op: 'move'
    data: [436, 666]
  - op: 'move'
    data: [522, 670]
  - op: 'patrol'
