author: ['DoctorReid', '龙女姬']
planet: '仙舟「罗浮」'
region: '丹鼎司'
floor: 1
tp: '观颐台'
route:
  - op: 'move'
    data: [443, 761]
  - op: 'move'
    data: [447, 846]
  - op: 'move'
    data: [445, 900]
  - op: 'move'
    data: [468, 931]
  - op: 'move'
    data: [499, 934]
  - op: 'move'
    data: [508, 848]
  - op: 'move'
    data: [532, 862]
  - op: 'patrol'
  - op: 'move'
    data: [532, 895]
  - op: 'patrol'
  - op: 'move'
    data: [533, 846]
  - op: 'move'
    data: [507, 848]
  - op: 'move'
    data: [503, 1029]
  - op: 'move'
    data: [501, 1123]
  - op: 'move'
    data: [614, 1125]
  - op: 'move'
    data: [608, 1255]
  - op: 'move'
    data: [635, 1276]
  - op: 'move'
    data: [651, 1264]
  - op: 'patrol'
