author: ['DoctorReid']
planet: '仙舟「罗浮」'
region: '丹鼎司'
floor: 2
tp: '行医市集'
route:
  - op: 'move'
    data: [866, 871]
  - op: 'move'
    data: [880, 766]
  - op: 'move'
    data: [884, 725]
  - op: 'move'
    data: [816, 660]
  - op: 'move'
    data: [795, 637]
  - op: 'move'
    data: [726, 573]
  - op: 'patrol'
