author: ['DoctorReid', '龙女姬']
planet: '仙舟「罗浮」'
region: '丹鼎司'
floor: 1
tp: '观颐台'
route:
  - op: 'move'
    data: [442, 751]
  - op: 'move'
    data: [446, 836]
  - op: 'move'
    data: [444, 890]
  - op: 'move'
    data: [467, 921]
  - op: 'move'
    data: [498, 924]
  - op: 'move'
    data: [507, 838]
  - op: 'move'
    data: [531, 852]
  - op: 'patrol'
  - op: 'move'
    data: [531, 885]
  - op: 'patrol'
  - op: 'move'
    data: [532, 836]
  - op: 'move'
    data: [506, 838]
  - op: 'move'
    data: [502, 1019]
  - op: 'move'
    data: [500, 1113]
  - op: 'move'
    data: [613, 1115]
  - op: 'move'
    data: [607, 1245]
  - op: 'move'
    data: [634, 1266]
  - op: 'move'
    data: [650, 1254]
  - op: 'patrol'
