author: ['DoctorReid']
planet: '仙舟「罗浮」'
region: '鳞渊境'
floor: 0
tp: '毁灭之蕾·拟造花萼（赤）'
route:
  - op: 'move'
    data: [882, 671]
  - op: 'move'
    data: [843, 638]
  - op: 'move'
    data: [793, 602]
  - op: 'move'
    data: [698, 586]
  - op: 'patrol'
  - op: 'move'
    data: [692, 549]
  - op: 'patrol'
