author: ['DoctorReid', '龙女姬']
planet: '仙舟「罗浮」'
region: '鳞渊境'
floor: 0
tp: '古海宫墟'
route:
  - op: 'move'
    data: [1127, 428]
  - op: 'move'
    data: [1127, 505]
  - op: 'move'
    data: [1147, 505]
  - op: 'move'
    data: [1141, 580]
  - op: 'patrol'
  - op: 'move'
    data: [1145, 607]
  - op: 'patrol'
  - op: 'move'
    data: [1110, 623]
  - op: 'patrol'
  - op: 'move'
    data: [1079, 607]
  - op: 'move'
    data: [1046, 607]
  - op: 'patrol'
  - op: 'move'
    data: [996, 609]
  - op: 'patrol'
  - op: 'move'
    data: [919, 607]
  - op: 'move'
    data: [917, 564]
  - op: 'patrol'
