author: ['DoctorReid']
planet: '仙舟「罗浮」'
region: '幽囚狱'
floor: -1
tp: '阴寒域·其一'
route:
  - idx: 1
    op: 'slow_move'
    data: [1237, 1294]
  - idx: 2
    op: 'interact'
    data: '按下'
  - idx: 3
    op: 'wait'
    data: ['seconds', '1']
  - idx: 4
    op: 'wait'
    data: ['in_world', '20']
  - idx: 5
    op: 'move'
    data: [1216, 1275]
  - idx: 6
    op: 'move'
    data: [1226, 1304]
  - idx: 7
    op: 'move'
    data: [1267, 1342]
  - idx: 8
    op: 'slow_move'
    data: [1282, 1380]
  - idx: 9
    op: 'interact'
    data: '按下'
  - idx: 10
    op: 'wait'
    data: ['seconds', '1']
  - idx: 11
    op: 'wait'
    data: ['in_world', '20']
  - idx: 12
    op: 'move'
    data: [1245, 1361]
  - idx: 13
    op: 'move'
    data: [1200, 1356]
  - idx: 14
    op: 'move'
    data: [1187, 1370]
  - idx: 15
    op: 'disposable'
  - idx: 16
    op: 'move'
    data: [1152, 1363]
  - idx: 17
    op: 'patrol'
  - idx: 18
    op: 'move'
    data: [1144, 1404]
  - idx: 19
    op: 'patrol'
  - idx: 20
    op: 'move'
    data: [1176, 1403]
  - idx: 21
    op: 'patrol'
  - idx: 22
    op: 'move'
    data: [1170, 1363]
  - idx: 23
    op: 'move'
    data: [1190, 1361]
  - idx: 24
    op: 'move'
    data: [1255, 1361]
  - idx: 25
    op: 'move'
    data: [1266, 1406]
  - idx: 26
    op: 'move'
    data: [1268, 1451]
  - idx: 27
    op: 'move'
    data: [1264, 1496]
  - idx: 28
    op: 'move'
    data: [1309, 1500]
  - idx: 29
    op: 'move'
    data: [1332, 1489]
  - idx: 30
    op: 'disposable'
  - idx: 31
    op: 'move'
    data: [1348, 1534]
  - idx: 32
    op: 'disposable'
  - idx: 33
    op: 'move'
    data: [1338, 1575]
  - idx: 34
    op: 'patrol'
  - idx: 35
    op: 'move'
    data: [1315, 1585]
  - idx: 36
    op: 'disposable'
  - idx: 37
    op: 'move'
    data: [1295, 1577]
  - idx: 38
    op: 'move'
    data: [1266, 1594]
  - idx: 39
    op: 'patrol'
  - idx: 40
    op: 'move'
    data: [1259, 1549]
  - idx: 41
    op: 'patrol'
