support_world: [3, 4, 5, 6, 7, 8]
planet: '雅利洛-VI'
region: '大矿区'
floor: 0
algo: 2
start_pos: [301, 482]
next_pos_list:
  - [268, 400]
op_list:
  - op: 'no_pos_move'
    data: [268, 430]
  - op: 'patrol'
