author: ['DoctorReid']
planet: '翁法罗斯'
region: '「命运重渊」雅努萨波利斯'
floor: 2
tp: '长梦宸扉'
route:
  - idx: 1
    op: 'move'
    data: [571, 1090]
  - idx: 2
    op: 'disposable'
  - idx: 3
    op: 'move'
    data: [477, 1111]
  - idx: 4
    op: 'move'
    data: [434, 1111, 1]
  - idx: 5
    op: 'move'
    data: [399, 1105]
  - idx: 6
    op: 'move'
    data: [403, 1068]
  - idx: 7
    op: 'move'
    data: [480, 1063]
  - idx: 8
    op: 'move'
    data: [482, 1086]
  - idx: 9
    op: 'patrol'
