author: ['DoctorReid']
planet: '翁法罗斯'
region: '「纷争荒墟」悬锋城'
floor: 1
tp: '琢石寂地'
route:
  - idx: 1
    op: 'move'
    data: [3163, 1068]
  - idx: 2
    op: 'wait'
    data: ['seconds', '4']
  - idx: 3
    op: 'move'
    data: [3186, 1066]
  - idx: 4
    op: 'move'
    data: [3196, 1085]
  - idx: 5
    op: 'move'
    data: [3231, 1083]
  - idx: 6
    op: 'move'
    data: [3240, 1084]
  - idx: 7
    op: 'patrol'
