author: ['DoctorReid']
planet: '翁法罗斯'
region: '「纷争荒墟」悬锋城'
floor: 1
tp: '止戈残间'
route:
  - idx: 1
    op: 'move'
    data: [1783, 1955]
  - idx: 2
    op: 'disposable'
  - idx: 3
    op: 'move'
    data: [1782, 1982]
  - idx: 4
    op: 'move'
    data: [1803, 1974]
  - idx: 5
    op: 'wait'
    data: ['in_world', '4']
  - idx: 6
    op: 'move'
    data: [1858, 1995]
  - idx: 7
    op: 'move'
    data: [1923, 1997]
  - idx: 8
    op: 'wait'
    data: ['in_world', '4']
  - idx: 9
    op: 'move'
    data: [1958, 1985, 2]
  - idx: 10
    op: 'move'
    data: [2000, 2004]
  - idx: 11
    op: 'patrol'
  - idx: 12
    op: 'move'
    data: [2016, 1969]
  - idx: 13
    op: 'disposable'
  - idx: 14
    op: 'move'
    data: [1988, 1966]
  - idx: 15
    op: 'disposable'
