author: ['DoctorReid']
planet: '翁法罗斯'
region: '「浴血战端」悬锋城'
floor: 1
tp: '弦歌之径·侵蚀隧洞'
route:
  - idx: 1
    op: 'move'
    data: [1162, 1001]
  - idx: 2
    op: 'patrol'
  - idx: 3
    op: 'move'
    data: [1222, 1000]
  - idx: 4
    op: 'wait'
    data: ['seconds', '4']
  - idx: 5
    op: 'move'
    data: [1242, 1024]
  - idx: 6
    op: 'disposable'
  - idx: 7
    op: 'move'
    data: [1303, 1051]
  - idx: 8
    op: 'patrol'
  - idx: 9
    op: 'move'
    data: [1324, 1041]
  - idx: 10
    op: 'disposable'
  - idx: 11
    op: 'move'
    data: [1190, 986]
  - idx: 12
    op: 'move'
    data: [1211, 890]
  - idx: 13
    op: 'disposable'
  - idx: 14
    op: 'move'
    data: [1298, 884]
  - idx: 15
    op: 'disposable'
  - idx: 16
    op: 'move'
    data: [1236, 886]
  - idx: 17
    op: 'move'
    data: [1245, 865]
  - idx: 18
    op: 'move'
    data: [1207, 784]
  - idx: 19
    op: 'patrol'
  - idx: 20
    op: 'move'
    data: [1172, 733]
  - idx: 21
    op: 'move'
    data: [1140, 721]
  - idx: 22
    op: 'disposable'
  - idx: 23
    op: 'move'
    data: [1189, 686]
  - idx: 24
    op: 'move'
    data: [1176, 625]
  - idx: 25
    op: 'disposable'
  - idx: 26
    op: 'move'
    data: [1213, 640]
  - idx: 27
    op: 'move'
    data: [1225, 616]
  - idx: 28
    op: 'move'
    data: [1217, 528]
  - idx: 29
    op: 'move'
    data: [1162, 520]
  - idx: 30
    op: 'move'
    data: [1187, 463]
  - idx: 31
    op: 'patrol'
  - idx: 32
    op: 'move'
    data: [1161, 520]
  - idx: 33
    op: 'move'
    data: [1100, 518]
  - idx: 34
    op: 'disposable'
  - idx: 35
    op: 'move'
    data: [1085, 593]
  - idx: 36
    op: 'disposable'
  - idx: 37
    op: 'move'
    data: [1122, 561]
  - idx: 38
    op: 'move'
    data: [1144, 583, 2]
  - idx: 39
    op: 'move'
    data: [1163, 596]
  - idx: 40
    op: 'disposable'
  - idx: 41
    op: 'move'
    data: [1194, 596]
  - idx: 42
    op: 'patrol'
  - idx: 43
    op: 'move'
    data: [1199, 564]
  - idx: 44
    op: 'move'
    data: [1219, 517]
  - idx: 45
    op: 'move'
    data: [1234, 464]
  - idx: 46
    op: 'patrol'
  - idx: 47
    op: 'move'
    data: [1213, 491]
  - idx: 48
    op: 'move'
    data: [1185, 469]
  - idx: 49
    op: 'disposable'
  - idx: 50
    op: 'move'
    data: [1129, 478]
  - idx: 51
    op: 'disposable'
