author: ['DoctorReid']
planet: '翁法罗斯'
region: '「穹顶关塞」晨昏之眼'
floor: 2
tp: '擎空骨械'
route:
  - idx: 1
    op: 'move'
    data: [1225, 1337]
  - idx: 2
    op: 'disposable'
  - idx: 3
    op: 'move'
    data: [1160, 1276]
  - idx: 4
    op: 'disposable'
  - idx: 5
    op: 'move'
    data: [1160, 1187]
  - idx: 6
    op: 'move'
    data: [1070, 1208]
  - idx: 7
    op: 'disposable'
  - idx: 8
    op: 'move'
    data: [1070, 1167]
  - idx: 9
    op: 'disposable'
  - idx: 10
    op: 'move'
    data: [1070, 1074]
  - idx: 11
    op: 'slow_move'
    data: [1069, 1038]
  - idx: 12
    op: 'move'
    data: [956, 1053]
  - idx: 13
    op: 'disposable'
  - idx: 14
    op: 'move'
    data: [970, 1009]
  - idx: 15
    op: 'slow_move'
    data: [969, 975]
  - idx: 16
    op: 'move'
    data: [994, 889]
  - idx: 17
    op: 'disposable'
  - idx: 18
    op: 'move'
    data: [962, 924]
  - idx: 19
    op: 'move'
    data: [937, 924]
  - idx: 20
    op: 'wait'
    data: ['seconds', '5']
  - idx: 21
    op: 'move'
    data: [872, 925]
  - idx: 22
    op: 'move'
    data: [861, 989]
  - idx: 23
    op: 'disposable'
  - idx: 24
    op: 'move'
    data: [829, 1030]
  - idx: 25
    op: 'disposable'
  - idx: 26
    op: 'move'
    data: [771, 1017]
  - idx: 27
    op: 'wait'
    data: ['seconds', '5']
  - idx: 28
    op: 'move'
    data: [688, 1015]
  - idx: 29
    op: 'move'
    data: [694, 844]
  - idx: 30
    op: 'move'
    data: [761, 843]
  - idx: 31
    op: 'move'
    data: [784, 861]
  - idx: 32
    op: 'patrol'
  - idx: 33
    op: 'move'
    data: [775, 821]
  - idx: 34
    op: 'patrol'
  - idx: 35
    op: 'move'
    data: [762, 842]
  - idx: 36
    op: 'move'
    data: [580, 842]
  - idx: 37
    op: 'move'
    data: [572, 886]
  - idx: 38
    op: 'patrol'
  - idx: 39
    op: 'move'
    data: [513, 885]
  - idx: 40
    op: 'disposable'
  - idx: 41
    op: 'move'
    data: [579, 843]
  - idx: 42
    op: 'move'
    data: [696, 845]
  - idx: 43
    op: 'move'
    data: [690, 1012]
  - idx: 44
    op: 'move'
    data: [644, 1012]
  - idx: 45
    op: 'move'
    data: [645, 1187]
  - idx: 46
    op: 'disposable'
  - idx: 47
    op: 'move'
    data: [531, 1193]
  - idx: 48
    op: 'patrol'
  - idx: 49
    op: 'move'
    data: [468, 1197]
  - idx: 50
    op: 'patrol'
