author: ['DoctorReid']
planet: '翁法罗斯'
region: '「纷争荒墟」悬锋城'
floor: 2
tp: '征伐陌地'
route:
  - idx: 1
    op: 'move'
    data: [2454, 1878]
  - idx: 2
    op: 'move'
    data: [2452, 1973]
  - idx: 3
    op: 'move'
    data: [2451, 1982]
  - idx: 4
    op: 'disposable'
  - idx: 5
    op: 'move'
    data: [2421, 1989]
  - idx: 6
    op: 'move'
    data: [2328, 1978]
  - idx: 7
    op: 'move'
    data: [2293, 1991]
  - idx: 8
    op: 'disposable'
  - idx: 9
    op: 'move'
    data: [2210, 1982]
  - idx: 10
    op: 'move'
    data: [2190, 1970]
  - idx: 11
    op: 'patrol'
  - idx: 12
    op: 'move'
    data: [2216, 1988]
  - idx: 13
    op: 'move'
    data: [2303, 1988]
  - idx: 14
    op: 'move'
    data: [2306, 2012]
  - idx: 15
    op: 'move'
    data: [2218, 2010]
  - idx: 16
    op: 'patrol'
