support_world: [8]
planet: '仙舟「罗浮」'
region: '流云渡'
floor: 1
start_pos: [475, 1378]
next_pos_list:
  - [398, 1391]
  - [398, 1368]
op_list:
  - op: 'move'
    data: [436, 1389]
  - op: 'patrol'
  - op: 'move'
    data: [421, 1389]
