support_world: [5, 6, 8]
planet: '仙舟「罗浮」'
region: '流云渡'
floor: 1
start_pos: [481, 1388]
next_pos_list:
  - [404, 1401]
  - [404, 1378]
op_list:
  - op: 'move'
    data: [436, 1389]
  - op: 'patrol'
  - op: 'move'
    data: [421, 1389]
