support_world: [5, 6, 7, 8]
planet: '仙舟「罗浮」'
region: '流云渡'
floor: 1
start_pos: [499, 1393]
next_pos_list:
  - [404, 1401]
  - [404, 1378]
op_list:
  - op: 'move'
    data: [436, 1393]
  - op: 'patrol'
  - op: 'move'
    data: [421, 1393]
