author: ['DoctorReid']
planet: '匹诺康尼'
region: '克劳克影视乐园'
floor: 2
tp: '哈努帮派基地'
route:
  - idx: 1
    op: 'move'
    data: [649, 1509]
  - idx: 2
    op: 'move'
    data: [661, 1531]
  - idx: 3
    op: 'patrol'
  - idx: 4
    op: 'move'
    data: [680, 1547]
  - idx: 5
    op: 'move'
    data: [646, 1576]
  - idx: 6
    op: 'patrol'
  - idx: 7
    op: 'move'
    data: [649, 1615]
  - idx: 8
    op: 'disposable'
