author: ['DoctorReid']
planet: '匹诺康尼'
region: '克劳克影视乐园'
floor: 2
tp: '哈努帮派基地'
route:
  - idx: 1
    op: 'move'
    data: [578, 1471]
  - idx: 2
    op: 'move'
    data: [564, 1406]
  - idx: 3
    op: 'move'
    data: [534, 1378]
  - idx: 4
    op: 'disposable'
  - idx: 5
    op: 'move'
    data: [438, 1419]
  - idx: 6
    op: 'patrol'
