author: ['DoctorReid']
planet: '匹诺康尼'
region: '朝露公馆'
floor: 1
tp: '梦主大厅'
route:
  - idx: 1
    op: 'move'
    data: [607, 429]
  - idx: 2
    op: 'move'
    data: [604, 352]
  - idx: 3
    op: 'move'
    data: [760, 351]
  - idx: 4
    op: 'disposable'
  - idx: 5
    op: 'move'
    data: [752, 416]
  - idx: 6
    op: 'move'
    data: [768, 441]
  - idx: 7
    op: 'patrol'
  - idx: 8
    op: 'move'
    data: [733, 441]
  - idx: 9
    op: 'patrol'
