author: ['DoctorReid']
planet: '匹诺康尼'
region: '「白日梦」酒店-梦境'
floor: 1
tp: '监控室'
route:
  - idx: 1
    op: 'move'
    data: [431, 555]
  - idx: 2
    op: 'disposable'
  - idx: 3
    op: 'move'
    data: [456, 587]
  - idx: 4
    op: 'move'
    data: [443, 682]
  - idx: 5
    op: 'disposable'
  - idx: 6
    op: 'move'
    data: [313, 681]
  - idx: 7
    op: 'patrol'
