author: ['DoctorReid']
planet: '匹诺康尼'
region: '匹诺康尼大剧院'
floor: 0
tp: '调弦大厅'
route:
  - idx: 1
    op: 'move'
    data: [733, 723]
  - idx: 2
    op: 'patrol'
  - idx: 3
    op: 'move'
    data: [721, 752]
  - idx: 4
    op: 'move'
    data: [680, 728]
  - idx: 5
    op: 'move'
    data: [655, 687]
  - idx: 6
    op: 'disposable'
  - idx: 7
    op: 'move'
    data: [620, 678]
  - idx: 8
    op: 'move'
    data: [593, 653]
  - idx: 9
    op: 'patrol'
  - idx: 10
    op: 'move'
    data: [591, 626]
  - idx: 11
    op: 'disposable'
  - idx: 12
    op: 'move'
    data: [549, 587]
  - idx: 13
    op: 'move'
    data: [536, 541]
  - idx: 14
    op: 'move'
    data: [531, 503]
  - idx: 15
    op: 'move'
    data: [564, 488]
  - idx: 16
    op: 'patrol'
  - idx: 17
    op: 'move'
    data: [499, 456]
  - idx: 18
    op: 'patrol'
  - idx: 19
    op: 'move'
    data: [456, 434]
  - idx: 20
    op: 'move'
    data: [427, 435]
  - idx: 21
    op: 'patrol'
