author: ['DoctorReid']
planet: '匹诺康尼'
region: '克劳克影视乐园'
floor: 2
tp: '仓鼠球乐园'
route:
  - idx: 1
    op: 'move'
    data: [699, 474]
  - idx: 2
    op: 'move'
    data: [727, 554]
  - idx: 3
    op: 'patrol'
  - idx: 4
    op: 'move'
    data: [667, 564]
  - idx: 5
    op: 'move'
    data: [659, 535]
  - idx: 6
    op: 'patrol'
