author: ['DoctorReid']
planet: '匹诺康尼'
region: '筑梦边境'
floor: 0
tp: '屋顶花园'
route:
  - op: 'move'
    data: [832, 1364]
  - op: 'move'
    data: [815, 1378]
  - op: 'patrol'
  - op: 'move'
    data: [832, 1364]
  - op: 'move'
    data: [833, 1308]
  - op: 'patrol'
  - op: 'move'
    data: [778, 1310]
  - op: 'patrol'
  - op: 'move'
    data: [729, 1315]
  - op: 'move'
    data: [718, 1443]
  - op: 'patrol'
