author: ['DoctorReid']
planet: '匹诺康尼'
region: '筑梦边境'
floor: 0
tp: '筑梦广场'
route:
  - op: 'move'
    data: [1277, 756]
  - op: 'move'
    data: [1277, 823]
  - op: 'move'
    data: [1216, 823]
  - op: 'move'
    data: [1210, 878]
  - op: 'move'
    data: [1213, 923]
  - op: 'patrol'
  - op: 'move'
    data: [1212, 999]
  - op: 'move'
    data: [1210, 1037]
  - op: 'patrol'
