author: ['DoctorReid']
planet: '匹诺康尼'
region: '筑梦边境'
floor: 0
tp: '回忆之蕾·拟造花萼（金）'
route:
  - idx: 1
    op: 'move'
    data: [301, 1364]
  - idx: 2
    op: 'patrol'
  - idx: 3
    op: 'move'
    data: [315, 1396]
  - idx: 4
    op: 'move'
    data: [315, 1455]
  - idx: 5
    op: 'move'
    data: [335, 1460]
  - idx: 6
    op: 'patrol'
