author: ['DoctorReid']
planet: '匹诺康尼'
region: '「白日梦」酒店-梦境'
floor: 3
tp: '贵宾休息室走廊'
route:
  - op: 'move'
    data: [606, 1025]
  - op: 'move'
    data: [606, 1122]
  - op: 'move'
    data: [606, 1158]
  - op: 'move'
    data: [505, 1228]
  - op: 'patrol'
  - op: 'move'
    data: [540, 1254]
  - op: 'patrol'
  - op: 'move'
    data: [601, 1247]
  - op: 'patrol'
  - op: 'move'
    data: [691, 1231]
  - op: 'move'
    data: [769, 1231]
  - op: 'move'
    data: [770, 1260]
  - op: 'patrol'
