author: ['DoctorReid']
planet: '匹诺康尼'
region: '「白日梦」酒店-梦境'
floor: 3
tp: '贵宾休息室走廊'
route:
  - op: 'move'
    data: [550, 1004]
  - op: 'move'
    data: [550, 1064]
  - op: 'move'
    data: [503, 1064]
  - op: 'patrol'
  - op: 'move'
    data: [444, 1058]
  - op: 'move'
    data: [441, 1007]
  - op: 'patrol'
