author: ['DoctorReid']
planet: '匹诺康尼'
region: '「白日梦」酒店-梦境'
floor: 3
tp: '铂金客房'
route:
  - idx: 1
    op: 'move'
    data: [1426, 684]
  - idx: 2
    op: 'move'
    data: [1409, 707]
  - idx: 3
    op: 'disposable'
  - idx: 4
    op: 'move'
    data: [1428, 788]
  - idx: 5
    op: 'disposable'
  - idx: 6
    op: 'move'
    data: [1421, 814]
  - idx: 7
    op: 'move'
    data: [1419, 859]
  - idx: 8
    op: 'slow_move'
    data: [1419, 919]
  - idx: 9
    op: 'move'
    data: [1383, 915]
  - idx: 10
    op: 'move'
    data: [1347, 916]
  - idx: 11
    op: 'patrol'
  - idx: 12
    op: 'move'
    data: [1291, 981]
  - idx: 13
    op: 'patrol'
  - idx: 14
    op: 'move'
    data: [1230, 916]
  - idx: 15
    op: 'patrol'
  - idx: 16
    op: 'move'
    data: [1173, 916]
  - idx: 17
    op: 'move'
    data: [1162, 968]
  - idx: 18
    op: 'patrol'
