author: ['DoctorReid']
planet: '匹诺康尼'
region: '「白日梦」酒店-梦境'
floor: 3
tp: '冰酿之形·凝滞虚影'
route:
  - idx: 1
    op: 'move'
    data: [289, 737]
  - idx: 2
    op: 'move'
    data: [276, 748]
  - idx: 3
    op: 'disposable'
  - idx: 4
    op: 'move'
    data: [319, 745]
  - idx: 5
    op: 'move'
    data: [347, 745]
  - idx: 6
    op: 'move'
    data: [346, 714]
  - idx: 7
    op: 'patrol'
  - idx: 8
    op: 'move'
    data: [346, 789]
  - idx: 9
    op: 'move'
    data: [384, 791]
  - idx: 10
    op: 'patrol'
  - idx: 11
    op: 'move'
    data: [433, 790]
  - idx: 12
    op: 'move'
    data: [434, 745]
  - idx: 13
    op: 'move'
    data: [476, 745]
  - idx: 14
    op: 'move'
    data: [476, 831]
  - idx: 15
    op: 'move'
    data: [472, 862]
  - idx: 16
    op: 'move'
    data: [393, 906]
  - idx: 17
    op: 'patrol'
  - idx: 18
    op: 'move'
    data: [449, 942]
  - idx: 19
    op: 'patrol'
  - idx: 20
    op: 'move'
    data: [470, 912]
  - idx: 21
    op: 'move'
    data: [545, 919]
  - idx: 22
    op: 'move'
    data: [610, 917]
  - idx: 23
    op: 'move'
    data: [622, 952]
  - idx: 24
    op: 'patrol'
  - idx: 25
    op: 'move'
    data: [620, 996]
  - idx: 26
    op: 'patrol'
