author: ['DoctorReid']
planet: '匹诺康尼'
region: '城市沙盒'
floor: 0
tp: '城市沙盒'
route:
  - idx: 1
    op: 'move'
    data: [900, 551]
  - idx: 2
    op: 'move'
    data: [1002, 550]
  - idx: 3
    op: 'move'
    data: [1010, 537]
  - idx: 4
    op: 'patrol'
  - idx: 5
    op: 'move'
    data: [1059, 535]
  - idx: 6
    op: 'patrol'
  - idx: 7
    op: 'move'
    data: [1034, 421]
  - idx: 8
    op: 'move'
    data: [1035, 362]
  - idx: 9
    op: 'patrol'
  - idx: 10
    op: 'move'
    data: [990, 344]
  - idx: 11
    op: 'patrol'
