author: ['DoctorReid']
planet: '匹诺康尼'
region: '朝露公馆'
floor: 1
tp: '梦主大厅'
route:
  - idx: 1
    op: 'move'
    data: [555, 462]
  - idx: 2
    op: 'disposable'
  - idx: 3
    op: 'move'
    data: [543, 357]
  - idx: 4
    op: 'move'
    data: [520, 339]
  - idx: 5
    op: 'move'
    data: [521, 294]
  - idx: 6
    op: 'move'
    data: [495, 289]
  - idx: 7
    op: 'move'
    data: [499, 323]
  - idx: 8
    op: 'slow_move'
    data: [502, 348, 2]
  - idx: 9
    op: 'move'
    data: [504, 433]
  - idx: 10
    op: 'patrol'
  - idx: 11
    op: 'move'
    data: [509, 462]
  - idx: 12
    op: 'patrol'
  - idx: 13
    op: 'move'
    data: [506, 479]
  - idx: 14
    op: 'move'
    data: [553, 502]
  - idx: 15
    op: 'move'
    data: [598, 503]
  - idx: 16
    op: 'move'
    data: [641, 476]
  - idx: 17
    op: 'disposable'
  - idx: 18
    op: 'move'
    data: [647, 400]
  - idx: 19
    op: 'move'
    data: [626, 399]
  - idx: 20
    op: 'patrol'
