author: ['DoctorReid']
planet: '匹诺康尼'
region: '朝露公馆'
floor: 1
tp: '梦主大厅'
route:
  - idx: 1
    op: 'move'
    data: [639, 733]
  - idx: 2
    op: 'disposable'
  - idx: 3
    op: 'move'
    data: [624, 632]
  - idx: 4
    op: 'move'
    data: [624, 556]
  - idx: 5
    op: 'slow_move'
    data: [596, 553]
  - idx: 6
    op: 'move'
    data: [595, 455]
  - idx: 7
    op: 'move'
    data: [562, 453]
  - idx: 8
    op: 'move'
    data: [561, 504]
  - idx: 9
    op: 'slow_move'
    data: [563, 550, 2]
  - idx: 10
    op: 'slow_move'
    data: [563, 577]
  - idx: 11
    op: 'move'
    data: [560, 631]
  - idx: 12
    op: 'move'
    data: [559, 682]
  - idx: 13
    op: 'patrol'
  - idx: 14
    op: 'move'
    data: [566, 736]
  - idx: 15
    op: 'move'
    data: [578, 733]
  - idx: 16
    op: 'patrol'
  - idx: 17
    op: 'move'
    data: [583, 760]
  - idx: 18
    op: 'move'
    data: [638, 799]
  - idx: 19
    op: 'move'
    data: [694, 798]
  - idx: 20
    op: 'move'
    data: [767, 744]
  - idx: 21
    op: 'disposable'
  - idx: 22
    op: 'move'
    data: [772, 625]
  - idx: 23
    op: 'move'
    data: [753, 625]
  - idx: 24
    op: 'patrol'
