author: ['DoctorReid']
planet: '匹诺康尼'
region: '克劳克影视乐园'
floor: 2
tp: '存护之蕾·拟造花萼（赤）'
route:
  - idx: 1
    op: 'move'
    data: [879, 1255]
  - idx: 2
    op: 'disposable'
  - idx: 3
    op: 'move'
    data: [862, 1306]
  - idx: 4
    op: 'move'
    data: [830, 1336]
  - idx: 5
    op: 'move'
    data: [761, 1331]
  - idx: 6
    op: 'patrol'
  - idx: 7
    op: 'move'
    data: [773, 1348]
  - idx: 8
    op: 'patrol'
