author: ['DoctorReid']
planet: '匹诺康尼'
region: '克劳克影视乐园'
floor: 1
tp: '影城大门'
route:
  - idx: 1
    op: 'move'
    data: [1187, 946]
  - idx: 2
    op: 'move'
    data: [1187, 984]
  - idx: 3
    op: 'move'
    data: [1125, 991]
  - idx: 4
    op: 'move'
    data: [985, 999]
  - idx: 5
    op: 'move'
    data: [935, 1000]
  - idx: 6
    op: 'move'
    data: [906, 1000]
  - idx: 7
    op: 'move'
    data: [888, 1022]
  - idx: 8
    op: 'disposable'
  - idx: 9
    op: 'move'
    data: [863, 1039]
  - idx: 10
    op: 'patrol'
