author: ['DoctorReid']
planet: '匹诺康尼'
region: '克劳克影视乐园'
floor: 2
tp: '哈努帮派基地'
route:
  - op: 'move'
    data: [649, 1509]
  - op: 'move'
    data: [661, 1531]
  - op: 'patrol'
  - op: 'move'
    data: [680, 1547]
  - op: 'move'
    data: [646, 1576]
  - op: 'patrol'
  - op: 'move'
    data: [649, 1615]
  - op: 'disposable'
