author: ['DoctorReid']
planet: '匹诺康尼'
region: '匹诺康尼大剧院'
floor: 0
tp: '上行长廊'
route:
  - idx: 1
    op: 'move'
    data: [796, 1418]
  - idx: 2
    op: 'move'
    data: [803, 1524]
  - idx: 3
    op: 'patrol'
  - idx: 4
    op: 'move'
    data: [780, 1422]
  - idx: 5
    op: 'move'
    data: [780, 1358]
  - idx: 6
    op: 'slow_move'
    data: [780, 1308]
  - idx: 7
    op: 'move'
    data: [815, 1286]
  - idx: 8
    op: 'move'
    data: [908, 1298]
  - idx: 9
    op: 'disposable'
  - idx: 10
    op: 'move'
    data: [953, 1274]
  - idx: 11
    op: 'patrol'
  - idx: 12
    op: 'move'
    data: [985, 1286]
  - idx: 13
    op: 'patrol'
