author: ['DoctorReid']
planet: '匹诺康尼'
region: '匹诺康尼大剧院'
floor: 0
tp: '交谊厅'
route:
  - idx: 1
    op: 'move'
    data: [1271, 812]
  - idx: 2
    op: 'disposable'
  - idx: 3
    op: 'move'
    data: [1211, 877]
  - idx: 4
    op: 'move'
    data: [1171, 917]
  - idx: 5
    op: 'move'
    data: [1132, 949]
  - idx: 6
    op: 'move'
    data: [1089, 962]
  - idx: 7
    op: 'patrol'
  - idx: 8
    op: 'move'
    data: [1076, 940]
  - idx: 9
    op: 'patrol'
