support_world: [3, 5, 6, 7, 8]
planet: '雅利洛-VI'
region: '大矿区'
floor: 0
algo: 1
start_pos: [853, 642]
next_pos_list:
  - [767, 564]
  - [786, 559]
op_list:
  - op: 'move'
    data: [818, 680]
  - op: 'move'
    data: [777, 721]
  - op: 'patrol'
  - op: 'move'
    data: [745, 704]
  - op: 'move'
    data: [766, 667]
  - op: 'patrol'
  - op: 'move'
    data: [782, 589]
  - op: 'patrol'
