support_world: [8]
planet: '仙舟罗浮'
region: '太卜司'
floor: 1
start_pos: [1015, 370]
next_pos_list:
  - [1023, 530]
  - [1007, 530]
op_list:
  - op: 'move'
    data: [1012, 439]
  - op: 'patrol'
  - op: 'move'
    data: [1013, 471]
  - op: 'patrol'
  - op: 'move'
    data: [1012, 510]
  - op: 'patrol'
