planet: '仙舟罗浮'
region: '廻星港'
floor: 2
start_pos: [857, 271]
next_pos_list:
  - [680, 289]
  - [680, 272]
op_list:
  - op: 'move'
    data: [805, 275]
  - op: 'patrol'
  - op: 'move'
    data: [785, 275]
  - op: 'move'
    data: [737, 275]
  - op: 'move'
    data: [705, 284]
  - op: 'patrol'
