planet: '雅利洛'
region: '铆钉镇'
floor: 1
start_pos: [703, 365]
op_list:
  - op: 'move'
    data: [708, 411]
  - op: 'patrol'
  - op: 'move'
    data: [736, 423]
  - op: 'move'
    data: [734, 460]
  - op: 'patrol'
  - op: 'move'
    data: [735, 531]
  - op: 'patrol'
