support_world: [3, 4, 8]
planet: '空间站黑塔'
region: '支援舱段'
floor: 2
start_pos: [271, 389]
next_pos_list:
  - [438, 317]
  - [437, 304]
op_list:
  - op: 'move'
    data: [271, 448]
  - op: 'move'
    data: [353, 451]
  - op: 'patrol'
  - op: 'move'
    data: [355, 395]
  - op: 'patrol'
  - op: 'move'
    data: [355, 317]
  - op: 'move'
    data: [428, 314]
  - op: 'patrol'
