support_world: [3, 8]
planet: '空间站黑塔'
region: '支援舱段'
floor: 2
start_pos: [281, 390]
next_pos_list:
  - [448, 318]
  - [447, 305]
op_list:
  - op: 'move'
    data: [281, 449]
  - op: 'move'
    data: [363, 452]
  - op: 'patrol'
  - op: 'move'
    data: [363, 396]
  - op: 'patrol'
  - op: 'move'
    data: [365, 318]
  - op: 'move'
    data: [438, 315]
  - op: 'patrol'
