support_world: [3, 4, 8]
planet: '空间站黑塔'
region: '支援舱段'
floor: 2
start_pos: [271, 389]
next_pos_list:
  - [438, 317]
  - [437, 304]
op_list:
  - op: 'move'
    data: [261, 447]
  - op: 'move'
    data: [343, 450]
  - op: 'patrol'
  - op: 'move'
    data: [345, 394]
  - op: 'patrol'
  - op: 'move'
    data: [345, 316]
  - op: 'move'
    data: [418, 313]
  - op: 'patrol'
